name: Java CI – Arccos Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: 🧪 Compile Java files
        run: javac ArccosConsole.java

      - name: ✅ Run program with test input (optional)
        run: |
          echo "0.5" | java ArccosConsole

      - name: 🚨 Fail if Java file missing
        if: failure()
        run: echo "Build failed!"
